### ISSUE TITLE
Use a custom kernel

### ISSUE THREAD

**Issue by 7k5x** [jaycedotbin/cfg#1]
Just had some spare time to browse Github in a while(No I'm not back yet).
Maybe you could use a custom kernel like linux-xanmod in the AUR(I use linux-xanmod-rt510, a realtime kernel).
Looks like you have a horrible Bulldozer CPU, so setting the architecture to 99(AMD GCC optimzations), disabling numa&&tracers, and using a local modprobed DB(those options are all in the PKGBUILD) would help your performance(The difference is pretty big).
This is just a suggestion, you don't really have to.

**Comment by jaycedotbin** [comment]
Hello, thank you for the recommendation, I think I will do that once I manage to get a comfortable working env in my config files. My current arch install is a mess atm so maybe once I have all of them organized I will try that.
